Intelligent Files Search/force-app/main/default/objects/ContentVersion/fields/content_text__c.field-meta.xml
<CustomField>
    <fullName>content_text__c</fullName>
    <label>content_text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

intelligent search/force-app/main/default/objects/ContentVersion/fields/parent_id__c.field-meta.xml
<CustomField>
    <fullName>parent_id__c</fullName>
    <label>parent_id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

intelligent search/force-app/main/default/classes/SearchFilesContentTest.cls
@isTest
public class SearchFilesContentTest {
    @isTest
    public static void testSearchContentVersionsByFields(){
        List<ContentVersion> cont_files  =  GenerateFilesHelper.start(6);
        cont_files[0].parent_id__c = cont_files[4].Id;
        cont_files[1].parent_id__c = cont_files[5].Id;
        cont_files[2].content_text__c = 'hello my name is api';
        cont_files[3].content_text__c = 'hello my name is apex';
        update cont_files;
        test.startTest();
        List<ContentVersion> returned  = SearchFilesContent.searchContentVersionsByFields('hello my name is api','all');
        List<ContentVersion> returned2 = SearchFilesContent.searchContentVersionsByTxt('text here', 'all');
        test.stopTest();
        System.assertEquals(2,returned2.size());
        System.assertEquals(0, returned.size());
        
    }

}