Intelligent Files Search/force-app/main/default/objects/ContentVersion/fields/content_text_2__c.field-meta.xml
<CustomField>
    <fullName>content_text_2__c</fullName>
    <label>content_text_2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Intelligent Files Search/force-app/main/default/objects/ContentVersion/fields/content_text_3__c.field-meta.xml
<CustomField>
    <fullName>content_text_3__c</fullName>
    <label>content_text_3</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Intelligent Files Search/force-app/main/default/objects/ContentVersion/fields/content_text__c.field-meta.xml
<CustomField>
    <fullName>content_text__c</fullName>
    <label>content_text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

intelligent search/force-app/main/default/classes/TextFilesCreatorTest.cls
@isTest
public class TextFilesCreatorTest{
    @isTest
    public static void test(){
        List<ContentVersion> cont_files = GenerateFilesHelper.start(1);
     
        
        String result = 'asadsddddddddddddddddddddddddddddddddddddddddddddddd';

       
        Map<Id,String> file_content = new Map<Id,String>();
        for(ContentVersion cont : cont_files){
            file_content.put(cont.Id,result);
           
          
        }
        
        Test.startTest();
        TextFilesCreator.create(file_content);
        Test.stopTest();
        ContentVersion updated_cont = [select Id,content_text__c,content_text_2__c,content_text_3__c from ContentVersion where Id = :cont_files[0].Id];
        System.Assert(updated_cont.content_text__c == result);
    }
}